baseURL = 'https://hugo-cinema.netlify.app/'
title = 'Cinema AN'

buildFuture = true

LanguageCode = "it"
DefaultContentLanguage = "it"

summaryLenght = 30

[params]
author = 'Daniele V'
csv = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQD3uxiiKqwRl-OcelK3u4OxXER95PT7PLYm_ihOuuD2TmHxiK1V_wHaNBrCvY9lpo1UCnB9C8rn8o9/pub?output=csv"
timeformat = "02/01/2006"

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menus.main]]
    name = "Programmazione"
    pageRef = "/film"
    URL= "progetti"
    weight = 20
  [[menus.main]]
    name = "Contatti"
    pageRef = "/contatti"
    weight = 30


[sitemap]
  changeFreq = 'always'
  disable = false
  filename = 'sitemap.xml'
  priority = -1


  [caches]
  [caches.getresource]
    maxAge = "1s"