baseURL = 'https://hugo-cinema.netlify.app/'
title = 'My New Hugo Site'

LanguageCode = "it"
DefaultContentLanguage = "it"
[languages]
  [languages.en]
    title = "My New Hugo i18n Site"
    languageName = "English"
    weight = 2
  [languages.it]
    title = "Î— Nuovo Sito"
    languageName = "Italian"
    weight = 1

[params]
author = 'Daniele V'