baseURL = 'https://hugo-cinema.netlify.app/'
title = 'My New Hugo Site'

defaultContentLanguage ="it"

[languages]
  [languages.it]
    disabled = false
    languageCode = 'it'
    languageDirection = ''
    languageName = 'Italian'
    title = 'Sito Italiano'
    weight = 0

[params]
author = 'Daniele V'